sonar.projectKey=memora
sonar.projectName=Memora
sonar.host.url=http://localhost:9000

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src/__tests__,backend/test
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/*.test.*,**/*.spec.*,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
