import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { X, Loader2 } from 'lucide-react'
import { useNotes } from '../context/NotesContext'
import noteService from '../services/noteService'
import toast from 'react-hot-toast'

export default function Scribby({ open, setOpen }) {
  const { addNote } = useNotes()
  const [prompt, setPrompt] = useState('')
  const [generating, setGenerating] = useState(false)

  const suggestions = [
    'Explain JavaScript closures',
    'Summarize React hooks',
    'Create notes about databases',
    'How does Node.js event loop work?',
  ]

  const handleGenerate = async (text) => {
    if (!text.trim()) return
    setGenerating(true)
    try {
      const res = await noteService.generateNote(text.trim())
      const { title, content } = res.note
      await addNote(title, content)
      setOpen(false)
      setPrompt('')
      toast.success('Note generated by Scribby')
    } catch {
      toast.error('Failed to generate note')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
          onClick={() => { if (!generating) setOpen(false) }}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            onClick={e => e.stopPropagation()}
            className="bg-[var(--bg-primary)] rounded-2xl shadow-2xl w-full max-w-lg p-6 border border-[var(--border)]"
          >
            <div className="flex items-center justify-between mb-5">
              <div className="flex items-center gap-3">
                <img src="/koala.png" alt="Scribby" className="w-10 h-10 rounded-xl" />
                <div>
                  <h2 className="text-base font-semibold text-[var(--text-primary)]">Scribby</h2>
                  <p className="text-xs text-[var(--text-secondary)]">AI-powered note generator</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => { if (!generating) setOpen(false) }}
                className="p-1.5 rounded-lg text-[var(--text-secondary)] hover:bg-[var(--bg-surface)] transition-colors"
              >
                <X size={18} />
              </button>
            </div>

            <div className="mb-4">
              <textarea
                value={prompt}
                onChange={e => setPrompt(e.target.value)}
                placeholder="Tell me what you'd like to take notes on..."
                rows={3}
                className="w-full px-4 py-3 rounded-xl border border-[var(--border)] bg-[var(--bg-primary)] text-[var(--text-primary)] placeholder:text-[var(--text-secondary)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/40 text-sm resize-none"
              />
            </div>

            <div className="mb-5">
              <p className="text-xs text-[var(--text-secondary)] mb-2">Try one of these:</p>
              <div className="flex flex-wrap gap-2">
                {suggestions.map(s => (
                  <button
                    type="button"
                    key={s}
                    onClick={() => setPrompt(s)}
                    className="text-xs px-3 py-1.5 rounded-lg border border-[var(--border)] text-[var(--text-secondary)] hover:bg-[var(--bg-surface)] transition-colors"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>

            <button
              type="button"
              onClick={() => handleGenerate(prompt)}
              disabled={!prompt.trim() || generating}
              className="w-full py-2.5 rounded-xl bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white font-medium text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {generating ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  Generating...
                </>
              ) : (
                'Generate Note'
              )}
            </button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}
